ModBus:
  - port: /dev/ttyUSB0
    baud: 9600
    boot_time: 100
    devices:
      - id: 1
        measure_reg: 257
        test_reg: 512
      - id: 3
        measure_reg: 257
        test_reg: 512
  - port: /dev/ttyUSB1
    baud: 9600
    boot_time: 100
    devices:
        - id: 3
          measure_reg: 257
          test_reg: 512
  - port: /dev/ttyUSB2
    baud: 9600
    boot_time: 100
    devices:
        - id: 2
          measure_reg: 257
          test_reg: 512
Uart:
  - port: /dev/ttyUSB3
    baud: 9600
    data_bit: 8
    stop_bit: 1
    parity_check: N
    boot_time: 100
  - port: /dev/ttyUSB4
    baud: 9600
    boot_time: 100
    data_bit: 8
    stop_bit: 1
    parity_check: N